app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
