api:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /api

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    #resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix:   /api/doc

oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
